## Lectura del csv

In [10]:
import pandas as pd 
import matplotlib.pyplot as plt 
df = pd.read_csv('product_activity.csv')

## Exploracion inicial:
**utilizacion de head(), info() y describe() para comprender mejor el contenido del dataset**

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8782 entries, 0 to 8781
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            8782 non-null   str
 1   created_at         8782 non-null   str
 2   country            8782 non-null   str
 3   plan_type          8782 non-null   str
 4   user_age           8028 non-null   float64
 5   post_id            8782 non-null   str
 6   post_category      8782 non-null   str
 7   post_created_at    8782 non-null   str
 8   votes_received     8782 non-null   int64
 9   user_total_posts   8782 non-null   int64
 10  days_since_signup  8782 non-null   int64
 11  device_type        8782 non-null   str
dtypes: float64(1), int64(3), str(8)
memory usage: 823.4 KB

In [2]:
df.head()

,user_id,created_at,country,plan_type,user_age,post_id,post_category,post_created_at,votes_received,user_total_posts,days_since_signup,device_type
0,U01988,2025-02-18T02:07:44,PY,pro,26.0,P0008515,sport,2025-05-07T20:55:28,7,16,78,mobile
1,U00236,2025-06-22T07:49:10,BR,free,27.0,P0001023,tech,2025-09-13T20:31:06,1,9,83,web
2,U00791,2024-02-12T02:45:45,CL,free,28.0,P0003405,tech,2024-02-14T05:17:48,11,2,2,mobile
3,U01522,2024-09-22T07:06:50,US,free,16.0,P0006524,finance,2024-09-24T07:51:34,5,2,2,web
4,U01092,2025-07-18T02:27:52,PY,free,NaN,P0004665,education,2025-07-24T04:56:56,7,2,6,mobile

In [3]:
df.describe()

          user_age  votes_received  user_total_posts  days_since_signup
count  8028.000000     8782.000000       8782.000000        8782.000000
mean     27.902591        6.918356          8.324186          29.479390
std       7.547052        5.127311          6.754906          36.819928
min      16.000000        0.000000          1.000000           0.000000
25%      22.000000        3.000000          4.000000           5.000000
50%      28.000000        6.000000          6.000000          17.000000
75%      33.000000        9.000000         11.000000          40.000000
max      58.000000       74.000000         39.000000         404.000000

**Conteo de nulos y duplicados exactos**

In [9]:
duplicates = df.duplicated().sum()
null_values = df.isnull().sum()
print(f'Total de filas duplicadas: {duplicates}')
print(f'Valores nulos por columna:\n{null_values}')

Total de filas duplicadas: 172
Valores nulos por columna:
user_id                0
created_at             0
country                0
plan_type              0
user_age             754
post_id                0
post_category          0
post_created_at        0
votes_received         0
user_total_posts       0
days_since_signup      0
device_type            0
dtype: int64

**Valores unicos y frecuencias de plan_type, post_category y device_type**

In [15]:
display(pd.DataFrame(df['plan_type'].value_counts()))
display(pd.DataFrame(df['post_category'].value_counts()))
display(pd.DataFrame(df['device_type'].value_counts()))

              count
plan_type
free           5978
pro            1460
enterprise      306
Free            208
 free           197
FREE            196
FreE            189
PRo              46
 pro             44
PRO              44
Pro              38
Pro              35
EnterPrise       13
ENTERPRISE       11
 enterprise       7
Enterprise        7
premium           1
vip               1
enterprise+       1

               count
post_category
tech            1187
life             913
sports           899
science          753
finance          739
gaming           727
music            614
health           601
education        592
travel           445
 tech             70
Tech              67
TECH              56
tehc              50
Life              46
Finance           44
 sport            42
sciense           42
gamming           40
 life             38
SPORTS            37
 finance          37
LIFE              36
Sports            36
 science          35
sporst            35
Gaming            35
Science           34
 gaming           33
SCIENCE           33
finanse           32
FINANCE           31
EDUCATION         31
educatoin         31
Music             28
healt             28
 health           26
Education         25
GAMING            22
 education        21
Health            21
MUSIC             21
lfe               21
 music            20
Travel            20
TRAVEL            19
HEALTH            18
 travel           16
trvael            16
musc              16
politics           1
mistery            1
sp0rts             1

             count
device_type
web           4416
mobile        3761
desktop        602
tablet           1
console          1
phone            1

In [18]:
dt_created_at = pd.to_datetime(df['created_at'], errors="coerce")
dt_post_created_at = pd.to_datetime(df['post_created_at'], errors="coerce")